const DEFAULT_BLUR = 2

const FETCH_TIMEOUT = 5000

const TAB_MIN_WIDTH = 300
const TAB_MIN_HEIGHT = 300

const DOCKBOX_ID = '__dockbox__'

const LOCALSTORAGE_FEEDITEMS_KEY = 'newsdash_feeditems'
const LOCALSTORAGE_SETTINGS_KEY = 'newsdash_settings'

const LIGHTNESS_MIN = -20
const LIGHTNESS_MAX = 20
const SATURATION_MIN = 0
const SATURATION_MAX = 100
const FETCH_INTERVAL_MIN = 5
const FETCH_INTERVAL_MAX = 60
const ITEMS_TO_KEEP_MIN = 10
const ITEMS_TO_KEEP_MAX = 1000
const MIN_COLUMN_WIDTH_DEFAULT = 300
const MIN_COLUMN_WIDTH_MIN = 100
const MIN_COLUMN_WIDTH_MAX = 1000

export {
  DEFAULT_BLUR,
  DOCKBOX_ID,
  FETCH_INTERVAL_MAX,
  FETCH_INTERVAL_MIN,
  FETCH_TIMEOUT,
  ITEMS_TO_KEEP_MAX,
  ITEMS_TO_KEEP_MIN,
  LIGHTNESS_MAX,
  LIGHTNESS_MIN,
  LOCALSTORAGE_FEEDITEMS_KEY,
  LOCALSTORAGE_SETTINGS_KEY,
  MIN_COLUMN_WIDTH_DEFAULT,
  MIN_COLUMN_WIDTH_MAX,
  MIN_COLUMN_WIDTH_MIN,
  SATURATION_MAX,
  SATURATION_MIN,
  TAB_MIN_HEIGHT,
  TAB_MIN_WIDTH,
}
